export const housesData = [
    {
      id: 1,
      type: 'House',
      name: 'Firlands',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/D9bJMXN/house1.png",
      country: 'United States',
      address: '7240C Argyle St. Lawndale, CA 90260',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '750',
      move: "One Month Later" 
    },
    {
      id: 2,
      type: 'House',
      name: 'Woodlandside',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/XX8WnKm/house2.png",
      country: 'Canada',
      address: '798 Talbot St. Bridgewater, NJ 08807',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '1400',
      move: "Next Month"
    },
    {
      id: 3,
      type: 'House',
      name: 'Primrose View',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/dr27RVh/house3.png",
      country: 'United States',
      address: '2 Glen Creek St. Alexandria, VA 22304',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '540',
      move: "Two Month Later" 
    },
    {
      id: 4,
      type: 'House',
      name: 'The Firs',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/C0TrJ6m/house4.png",
      country: 'Canada',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '2200',
      move: "Next Month" 
    },
    {
      id: 5,
      type: 'House',
      name: 'Primroseways',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/4222xN5/house5.png",
      country: 'United States',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '5',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2015',
      price: '2050',
      move: "Two Month Later" 
    },
    {
      id: 6,
      type: 'House',
      name: 'Ford Lodge',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/556jSPv/house6.png",
      country: 'Canada',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '6',
      bathrooms: '3',
      surface: '6200 sq ft',
      year: '2014',
      price: '1570',
      move: "One Month Later"
    },
    {
      id: 7,
      type: 'Apartament',
      name: 'Owls End',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/Tv6xcTW/a1.png",
      country: 'Canada',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1200 sq ft',
      year: '2012',
      price: '920',
      move: "One Month Later" 
    },
    {
      id: 8,
      type: 'Apartament',
      name: 'Oak Bank',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/ckRv4gw/a2.png",
      country: 'United States',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1000 sq ft',
      year: '2011',
      price: '1380',
      move: "Two Month Later" 
    },
    {
      id: 9,
      type: 'Apartament',
      name: 'Pear House',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/SmCMqXP/a3.png",
      country: 'United States',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1100 sq ft',
      year: '2011',
      price: '650',
      move: "Next Month" 
    },
    {
      id: 10,
      type: 'House',
      name: 'Ginger House',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/mTkgBNb/house7.png",
      country: 'Canada',
      address: '7240C Argyle St. Lawndale, CA 90260',
      bedrooms: '5',
      bathrooms: '3',
      surface: '3200 sq ft',
      year: '2015',
      price: '2500',
      move: "Two Month Later" 
    },
    {
      id: 11,
      type: 'House',
      name: 'The Honeysuckles',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/zfMksTn/house8.png",
      country: 'Canada',
      address: '798 Talbot St. Bridgewater, NJ 08807',
      bedrooms: '7',
      bathrooms: '2',
      surface: '2200 sq ft',
      year: '2019',
      price: '2430',
      move: "Next Month" 
    },
    {
      id: 12,
      type: 'House',
      name: 'Mill House',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/p2n8NTT/house9.png",
      country: 'United States',
      address: '2 Glen Creek St. Alexandria, VA 22304',
      bedrooms: '4',
      bathrooms: '4',
      surface: '4600 sq ft',
      year: '2015',
      price: '1750',
      move: "One Month Later"
    },
    {
      id: 13,
      type: 'House',
      name: 'Meadow View',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/R75HDRs/house10.png",
      country: 'Canada',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '5',
      bathrooms: '2',
      surface: '5200 sq ft',
      year: '2014',
      price: '1280',
      move: "Next Month" 
    },
    {
      id: 14,
      type: 'House',
      name: 'Chilly End',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/nc3rMGX/house11.png",
      country: 'United States',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '5',
      bathrooms: '2',
      surface: '3200 sq ft',
      year: '2011',
      price: '1780',
      move: "Two Month Later"
    },
    {
      id: 15,
      type: 'House',
      name: 'Meadoways',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/cv8H410/house12.png",
      country: 'Canada',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '4',
      bathrooms: '3',
      surface: '5200 sq ft',
      year: '2013',
      price: '870',
      move: "Next Month" 
    },
    {
      id: 16,
      type: 'Apartament',
      name: 'London Lodge',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/8Y8jN44/a4.png",
      country: 'Canada',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1300 sq ft',
      year: '2011',
      price: '620',
      move: "One Month Later"
    },
    {
      id: 17,
      type: 'Apartament',
      name: 'Orchard View',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/CBjwLxn/a5.png",
      country: 'United States',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1000 sq ft',
      year: '2012',
      price: '745',
      move: "Next Month" 
    },
    {
      id: 18,
      type: 'Apartament',
      name: 'Orchardside',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/QKkvwfq/a6.png",
      country: 'Canada',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1200 sq ft',
      year: '2010',
      price: '895',
      move: "One Month Later"
    },
    {
      id: 19,
      type: 'House',
      name: 'Firlands',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/D9bJMXN/house1.png",
      country: 'Canada',
      address: '7240C Argyle St. Lawndale, CA 90260',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '750',
      move: "One Month Later" 
    },
    {
      id: 20,
      type: 'House',
      name: 'Woodlandside',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/XX8WnKm/house2.png",
      country: 'United States',
      address: '798 Talbot St. Bridgewater, NJ 08807',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '1400',
      move: "Next Month"
    },
    {
      id: 21,
      type: 'House',
      name: 'Primrose View',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/dr27RVh/house3.png",
      country: 'Canada',
      address: '2 Glen Creek St. Alexandria, VA 22304',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '540',
      move: "Two Month Later" 
    },
    {
      id: 22,
      type: 'House',
      name: 'The Firs',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/C0TrJ6m/house4.png",
      country: 'United States',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '6',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2016',
      price: '2200',
      move: "Next Month" 
    },
    {
      id: 23,
      type: 'House',
      name: 'Primroseways',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/4222xN5/house5.png",
      country: 'Canada',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '5',
      bathrooms: '3',
      surface: '4200 sq ft',
      year: '2015',
      price: '2050',
      move: "Two Month Later" 
    },
    {
      id: 24,
      type: 'House',
      name: 'Ford Lodge',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/556jSPv/house6.png",
      country: 'United States',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '6',
      bathrooms: '3',
      surface: '6200 sq ft',
      year: '2014',
      price: '1570',
      move: "One Month Later"
    },
    {
      id: 25,
      type: 'Apartament',
      name: 'Owls End',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/Tv6xcTW/a1.png",
      country: 'United States',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1200 sq ft',
      year: '2012',
      price: '920',
      move: "One Month Later" 
    },
    {
      id: 26,
      type: 'Apartament',
      name: 'Oak Bank',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/ckRv4gw/a2.png",
      country: 'Canada',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1000 sq ft',
      year: '2011',
      price: '1380',
      move: "Two Month Later" 
    },
    {
      id: 27,
      type: 'Apartament',
      name: 'Pear House',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/SmCMqXP/a3.png",
      country: 'Canada',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1100 sq ft',
      year: '2011',
      price: '650',
      move: "Next Month" 
    },
    {
      id: 28,
      type: 'House',
      name: 'Ginger House',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/mTkgBNb/house7.png",
      country: 'United States',
      address: '7240C Argyle St. Lawndale, CA 90260',
      bedrooms: '5',
      bathrooms: '3',
      surface: '3200 sq ft',
      year: '2015',
      price: '2500',
      move: "Two Month Later" 
    },
    {
      id: 29,
      type: 'House',
      name: 'The Honeysuckles',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/zfMksTn/house8.png",
      country: 'United States',
      address: '798 Talbot St. Bridgewater, NJ 08807',
      bedrooms: '7',
      bathrooms: '2',
      surface: '2200 sq ft',
      year: '2019',
      price: '2430',
      move: "Next Month" 
    },
    {
      id: 30,
      type: 'House',
      name: 'Mill House',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/p2n8NTT/house9.png",
      country: 'Canada',
      address: '2 Glen Creek St. Alexandria, VA 22304',
      bedrooms: '4',
      bathrooms: '4',
      surface: '4600 sq ft',
      year: '2015',
      price: '1750',
      move: "One Month Later"
    },
    {
      id: 31,
      type: 'House',
      name: 'Meadow View',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/R75HDRs/house10.png",
      country: 'United States',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '5',
      bathrooms: '2',
      surface: '5200 sq ft',
      year: '2014',
      price: '1280',
      move: "Next Month" 
    },
    {
      id: 32,
      type: 'House',
      name: 'Chilly End',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/nc3rMGX/house11.png",
      country: 'Canada',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '5',
      bathrooms: '2',
      surface: '3200 sq ft',
      year: '2011',
      price: '1780',
      move: "Two Month Later"
    },
    {
      id: 33,
      type: 'House',
      name: 'Meadoways',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/cv8H410/house12.png",
      country: 'United States',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '4',
      bathrooms: '3',
      surface: '5200 sq ft',
      year: '2013',
      price: '870',
      move: "Next Month" 
    },
    {
      id: 34,
      type: 'Apartament',
      name: 'London Lodge',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/8Y8jN44/a4.png",
      country: 'United States',
      address: '32 Pawnee Street Butte, MT 59701',
      bedrooms: '2',
      bathrooms: '1',
      surface: '1300 sq ft',
      year: '2011',
      price: '620',
      move: "One Month Later"
    },
    {
      id: 35,
      type: 'Apartament',
      name: 'Orchard View',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/CBjwLxn/a5.png",
      country: 'Canada',
      address: '28 Westport Dr. Warminster, PA 18974',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1000 sq ft',
      year: '2012',
      price: '745',
      move: "Next Month" 
    },
    {
      id: 36,
      type: 'Apartament',
      name: 'Orchardside',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illoat. Repudiandae ratione impedit delectus consectetur. Aspernaturvero obcaecati placeat ab distinctio unde ipsam molestias atqueratione delectus blanditiis nemo eius dignissimos doloremque quaealiquid maiores id tempore consequatur, quod pariatur saepe.',
      image: "https://i.ibb.co/QKkvwfq/a6.png",
      country: 'United States',
      address: '84 Woodland St. Cocoa, FL 32927',
      bedrooms: '3',
      bathrooms: '1',
      surface: '1200 sq ft',
      year: '2010',
      price: '895',
      move: "One Month Later"
    },
  ];